"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_os_username_bg)\
$os\
$username\
[](bg:color_directory_bg fg:color_os_username_bg)\
$directory\
[](fg:color_directory_bg bg:color_git_bg)\
$git_branch\
$git_status\
[](fg:color_git_bg bg:color_language_bg)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$kotlin\
$php\
$python\
[](fg:color_language_bg bg:color_docker_conda_bg)\
$docker_context\
$conda\
[](fg:color_docker_conda_bg bg:color_time_bg)\
$time\
[ ](fg:color_time_bg)\
$line_break$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

palette = 'pastel'

[palettes.pastel]
color_os_username_bg = '#9a348e'
color_directory_bg = '#da627d'
color_git_bg = '#fca17d'
color_language_bg = '#86bbd8'
color_docker_conda_bg = '#06969a'
color_time_bg = '#33658a'
color_green = '#559e83'
color_purple = '#c9c9ff'
color_red = '#ff8b94'
color_yellow = '#f3ffa3'

[os]
disabled = false
style = "bg:color_os_username_bg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_os_username_bg"
style_root = "bg:color_os_username_bg"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:color_directory_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dev" = "󰲋 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:color_git_bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_git_bg"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:color_language_bg"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:color_docker_conda_bg"
format = '[ $symbol( $context) ]($style)'

[conda]
style = "bg:color_docker_conda_bg"
format = '[ $symbol( $environment) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:color_time_bg"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
